on:
  push:
    branches:
      - 'release-please**'

name: Validate Release
jobs:
  npm-release:
    runs-on: ubuntu-latest
    steps:
      # The logic below handles the npm publication:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          cache: 'npm'

      - name: Attempt @openfeature/core Update
        run: | # also check branch?
          gh pr list --search --json '"release core" in:title'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push changes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: git push
