on:
  push:
    branches:
      - 'release-please**'
  schedule:
    - cron: '59 0 * * *' # once a day
  workflow_dispatch:     # on demand

env:
  CORE_PACKAGE: core

name: Audit Pending Releases
jobs:
  npm-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}

      - name: Check for Pending Dependency PRs
        if: ${{ !endsWith(github.ref_name, env.CORE_PACKAGE) }}
        run: |
          if [ $(gh pr list --search '"release ${{ env.CORE_PACKAGE }}" in:title' | wc -l) -gt 0 ]; \
            then echo "Pending @openfeaure/${{ env.CORE_PACKAGE }} release. Please release @openfeaure/${{ env.CORE_PACKAGE }} first!" && exit 1; \
            else echo "No pending @openfeaure/${{ env.CORE_PACKAGE }} releases"; \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          cache: 'npm'

      - name: Update Peer Version in Dependants
        if: ${{ endsWith(github.ref_name, env.CORE_PACKAGE) }}
        run: |
          npm run update-core-peers
          if git diff-files --quiet; \
            then exit 0; \
            else git config user.name "openfeature-peer-update-bot" && \
            git config user.email "openfeature-peer-update-bot@openfeature.dev" && \
            git commit -m 'chore: bump @openfeaure/${{ env.CORE_PACKAGE }} peer' -s && \
            git push; \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


