on:
  push:
    branches:
      - 'release-please**'

env:
  CORE_PACKAGE: core

name: Validate Release
jobs:
  npm-release:
    runs-on: ubuntu-latest
    steps:
      # The logic below handles the npm publication:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          cache: 'npm'

      - name: asd
        run: gh pr list --search '"release ${{ env.CORE_PACKAGE }}" in:title' | wc -l
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: dsa
        run: gh pr list --search '"release ${{ env.CORE_PACKAGE }}" in:title'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attempt @openfeature/core Update
        if: ${{ !endsWith(github.ref_name, env.CORE_PACKAGE) }}
        run: |
          if [ $(gh pr list --search '"release ${{ env.CORE_PACKAGE }}" in:title' | wc -l) -gt 0 ]; \
            then echo "Pending @openfeaure/${{ env.CORE_PACKAGE }} release. Please release @openfeaure/${{ env.CORE_PACKAGE }} first!" && exit 1; \
            else echo "No pending @openfeaure/${{ env.CORE_PACKAGE }} releases"; \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push changes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: git push
